name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Run CMake
        uses: lukka/run-cmake@v2
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'
          cmakeBuildType: 'Release'
          cmakeToolchainPath: '${{ github.workspace }}/.github/workflows/toolchain.cmake'
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/build'